version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-logo-cycler
    volumes:
      - ./logos:/app/logos
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 