version: '3.8'

services:
  discord-bot:
    build: 
      context: .
      platform: linux/amd64
    container_name: discord-logo-cycler
    volumes:
      - type: bind
        source: ./logos
        target: /app/logos
        read_only: true
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 